### ISSUE TITLE
Local storage driver

### ISSUE THREAD

**Issue by rgl** [sapcc/keppel#122]
Is there a storage driver that could use the local filesystem? Or a remote S3 like one (e.g. minio)?

**Comment by SuperSandro2000** [comment]
Keppel currently only supports swift and in-memory (for testing only) storage drivers.

If you would want to implement a local or s3 storage driver it would need to implement [this](https://github.com/sapcc/keppel/blob/master/internal/keppel/storage_driver.go#L31-L79) interface. You can take a look at the [trivial storage driver](https://github.com/sapcc/keppel/blob/master/internal/drivers/trivial/storage.go) and [swift driver](https://github.com/sapcc/keppel/blob/master/internal/drivers/openstack/swift.go) for an implementation of that interface. At the time of writing we don't have plans to implement a new driver because so far we had no requirement for it.

**Comment by rgl** [comment]
Thanks for the pointers. I will try to implement an s3 one. Would this be something that would be acceptable as a PR?

**Comment by rgl** [comment]
I've actually started with the filesystem driver.

Can you have a look at https://github.com/rgl/keppel/pull/1? If you agree, I can make a PR to this repository instead.

**Comment by rgl** [comment]
Should we also modify the `trivial` driver to a memory fs (`afero.NewMemMapFs()`)? Or do that in another PR?

**Comment by SuperSandro2000** [comment]
I would put that back for now. We may explore replacing the trivial driver completely with the filesystem driver because it should make debugging much easier but we haven't decided on that yet.
