### ISSUE TITLE
Transport received Server's graceful shutdown GOAWAY

### ISSUE THREAD

**Issue by edmarr** [sapcc/keppel#34]
Hi guys,

Sometimes I'm having this problem using keppel. To work around this, you need to retry the job to build/push the image again.

How can I solve this?

`error pushing image: failed to push to destination keppel.xxxxxxxxx:1.0.0.6: Patch "https://keppel.xxxxxxxxx/blobs/uploads/1a7f8560-6aca-4354-8adc-3e9c19fae0fa": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error
`

**Comment by majewsky** [comment]
In my opinion, that's a question for the client that does the pushing. In a distributed system, you always have to expect that connections may get randomly closed e.g. because of intermittent network issues (which I assume is what happened here). Therefore a competent client would retry failed transfers. `docker push` does this, it does a retry with proper exponential backoff for each blob push and each manifest push. If the client you're using is not willing to implement proper retry, consider using `docker push` instead.
