### ISSUE TITLE
Offloading accounts & permissions to external source

### ISSUE THREAD

**Issue by bittermandel** [sapcc/keppel#342]
As it looks right now, Keppel seems to depend on operators creating accounts in the Keppel database and set permissions for them there. This does not really fit into many environments, as operators generally store their authentication & authorization data in a centralized store and distribute it at that layer.

Would there be a possibility to consider moving it into an interface so it can be extended? We'd love to handle all authz/n externally from Keppel.

**Comment by SuperSandro2000** [comment]
We are configuring keppel through [elektra](https://github.com/sapcc/elektra/) which in the background uses keppels' API. Elektra is built to work with openstack and probably not easily adapted to be used in a more generic environment. We have a handful of accounts which we configure globally with a simple script through the API and the vast majority is done by the customers, as we only offer the registry platform.

OpenStack is designed around "domains" in which admins can create the keppel accounts where users can then do their things. Since we are all admins, we probably didn't notice yet that some of those settings are not as convenient and generic designed. If you are referring to this part.
So you're usecase would be that polices/RBACPolicies [checked here](https://github.com/sapcc/keppel/blob/d6c90317882242e0186d12cf8b3f18c46ead8e40/internal/auth/filter.go#L178-L206) or taken [here when creating the account](https://github.com/sapcc/keppel/blob/d6c90317882242e0186d12cf8b3f18c46ead8e40/internal/api/keppel/accounts.go#L415C2-L423) are taken from a central place through an extensible driver instead of from the database? Did I understand that correct?

But the generic request authz should already be extensible through the auth driver https://github.com/sapcc/keppel/blob/master/internal/auth/request.go#L139 
If a handful of functions should be moved into the auth driver, then I think that's easily possible. If we would need to create a complete new interface, then I would first design that with @majewsky .

Can you point a specific code path or api request you have in mind that is now hardwired into keppel to help me better understand your use case?

**Comment by majewsky** [comment]
I let the above design simmer in my head for a few days and did not see any obvious problems with it. I did #349 and #351 as a bit of a prerequisite for the addition of this new driver interface, and I will probably have @SuperSandro2000 drive the implementation of the new driver interface as well as the driver implementation for our seeding usecase.

**Comment by majewsky** [comment]
So it's been quite a while, but we added the AccountManagementDriver interface over the last few months, and I have now converted our own existing script-based seeding into a config deployment using the initial `basic` AccountManagementDriver. If you are still interested in using Keppel, you can now look into adding your own AccountManagementDriver implementation.
